apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clinical-unit
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  tls:
    - hosts:
        - AKS_HOST_PLACEHOLDER
      secretName: clinical-unit-tls
  rules:
    - host: AKS_HOST_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clinical-unit-frontend
                port:
                  name: http