# syntax=docker/dockerfile:1.7
FROM --platform=$BUILDPLATFORM node:22-alpine AS build

ARG NPM_REGISTRY=https://registry.npmjs.org/

ENV NPM_CONFIG_AUDIT=false \
    NPM_CONFIG_FETCH_RETRIES=5 \
    NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000 \
    NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000 \
    NPM_CONFIG_FUND=false \
    NPM_CONFIG_REGISTRY=${NPM_REGISTRY}

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    if [ -f package-lock.json ]; then npm ci; else npm install; fi

COPY . .

ARG VITE_AZURE_CLIENT_ID=__VITE_AZURE_CLIENT_ID__
ARG VITE_AZURE_AUTHORITY=__VITE_AZURE_AUTHORITY__
ARG VITE_AZURE_REDIRECT_URI=__VITE_AZURE_REDIRECT_URI__
ARG VITE_AZURE_TENANT_ID=__VITE_AZURE_TENANT_ID__
ARG VITE_CLINICAL_STAFF_GROUP_ID=__VITE_CLINICAL_STAFF_GROUP_ID__
ARG VITE_ADMIN_GROUP_ID=__VITE_ADMIN_GROUP_ID__
ARG VITE_AZURE_DOMAIN_HINT=__VITE_AZURE_DOMAIN_HINT__
ARG VITE_API_SCOPE=__VITE_API_SCOPE__

ENV VITE_AZURE_CLIENT_ID=${VITE_AZURE_CLIENT_ID} \
    VITE_AZURE_AUTHORITY=${VITE_AZURE_AUTHORITY} \
    VITE_AZURE_REDIRECT_URI=${VITE_AZURE_REDIRECT_URI} \
    VITE_AZURE_TENANT_ID=${VITE_AZURE_TENANT_ID} \
    VITE_CLINICAL_STAFF_GROUP_ID=${VITE_CLINICAL_STAFF_GROUP_ID} \
    VITE_ADMIN_GROUP_ID=${VITE_ADMIN_GROUP_ID} \
    VITE_AZURE_DOMAIN_HINT=${VITE_AZURE_DOMAIN_HINT} \
    VITE_API_SCOPE=${VITE_API_SCOPE} \
    VITE_API_URL=""

RUN npm run build

FROM --platform=$TARGETPLATFORM nginxinc/nginx-unprivileged:1.29-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY .migration-build/default.conf /etc/nginx/conf.d/default.conf
COPY .migration-build/40-runtime-config.sh /docker-entrypoint.d/40-runtime-config.sh

USER root
RUN chmod 0555 /docker-entrypoint.d/40-runtime-config.sh \
    && chgrp -R 0 /usr/share/nginx/html /etc/nginx/conf.d \
    && chmod -R g=u /usr/share/nginx/html /etc/nginx/conf.d
USER 101:0

EXPOSE 8080