apiVersion: v1
kind: Service
metadata:
  name: clinical-unit-frontend
  labels:
    app.kubernetes.io/name: clinical-unit-frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: clinical-unit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clinical-unit-frontend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP